apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cds-ai-codereviewer
  description: >-
    CDS AI Code Reviewer: Enhance your GitHub workflow with AI-powered code
    review! Get intelligent feedback and suggestions on pull requests using
    OpenAI's GPT-4 API, improving code quality and saving developers time.
  labels:
    license: MIT
spec:
  type: website
  lifecycle: experimental
  owner: cds-snc
